"""Fix errors

Revision ID: 8f50c51c35d7
Revises: b3b75c2754f1
Create Date: 2021-05-29 22:59:38.709210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f50c51c35d7'
down_revision = 'b3b75c2754f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_InPatients_patient_Patients', 'InPatients', type_='foreignkey')
    op.drop_column('InPatients', 'patient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InPatients', sa.Column('patient', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_InPatients_patient_Patients', 'InPatients', 'Patients', ['patient'], ['id'])
    # ### end Alembic commands ###
